# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.231.6/containers/ubuntu/.devcontainer/base.Dockerfile


# [Choice] Ubuntu version (use hirsuite or bionic on local arm64/Apple Silicon): hirsute, focal, bionic
ARG VARIANT="focal"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}


USER vscode

RUN sudo apt update
RUN sudo apt install -y protobuf-compiler=3.6.1.3-2ubuntu5 protobuf-compiler-grpc=1.16.1-1ubuntu5

# Enable autocompletion
RUN echo "source <(ng completion script)" >> /home/vscode/.bashrc

CMD [ "sleep", "infinity" ]