PROTO_DIR := ../protobuf

BUILD_DIR := internal

PROTO_FLAGS := --proto_path $(PROTO_DIR)

PROTO_SOURCES := $(shell find $(PROTO_DIR) -name '*.proto')
PROTO_FILES := $(PROTO_SOURCES:$(PROTO_DIR)/%.proto=$(BUILD_DIR)/%.pb.ts)

PROTOC := protoc

PROTOC_GEN_PROTO := ./node_modules/.bin/protoc-gen-ts
PROTO_FLAGS += --plugin=protoc-gen-ts=$(PROTOC_GEN_PROTO)


$(BUILD_DIR)/%.pb.ts: $(PROTO_DIR)/%.proto
	echo $<

$(BUILD_DIR)/%.pb.ts: $(PROTO_DIR)/%.proto
	$(PROTOC) $< --ts_out="service=grpc-web:$(BUILD_DIR)" --js_out="import_style=commonjs,binary:$(BUILD_DIR)" $(PROTO_FLAGS)

protobuf: $(BUILD_DIR) $(PROTO_FILES)


clean:
	npm install ts-protoc-gen @improbable-eng/grpc-web @types/google-protobuf google-protobuf
