version: '3.8'

services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: focal
    volumes:
      - ..:/workspace:cached
    user: vscode
    command: sleep infinity
